version: '3.9'

networks:
  net:
    driver: bridge

services:
  server:
    image: server
    build:
      context: ../chroma
      dockerfile: Dockerfile
    volumes:
      - ../chroma:/chroma
      - index_data:/index_data
    command: uvicorn chromadb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - 8000:8000
    networks:
      - net

  claire:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHROMA_URL=http://server:8000
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local
